package demo;
// Generated Dec 12, 2020 12:39:01 PM by Hibernate Tools 4.3.1



/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private int employeeid;
     private String employeename;

    public Employees() {
    }

	
    public Employees(int employeeid) {
        this.employeeid = employeeid;
    }
    public Employees(int employeeid, String employeename) {
       this.employeeid = employeeid;
       this.employeename = employeename;
    }
   
    public int getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(int employeeid) {
        this.employeeid = employeeid;
    }
    public String getEmployeename() {
        return this.employeename;
    }
    
    public void setEmployeename(String employeename) {
        this.employeename = employeename;
    }




}


